version: '3'

tasks:
  gen-db:
    cmds:
      - sqlc generate
    desc: Generate SQLC code
  migrate:
    cmds:
      - goose -dir ./internal/db/schema/migrations sqlite3 ./c-ademy.db up
  start-api:
    cmds:
      - go run ./api/cmd/main.go
    desc: Start API server