// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"database/sql"
)

type Allowlist struct {
	ID        int64
	Username  string
	IsAllowed bool
	CreatedAt sql.NullTime
}

type ApiToken struct {
	ID        int64
	UserID    int64
	Token     string
	ExpiresAt sql.NullTime
	CreatedAt sql.NullTime
}

type Execution struct {
	ID             int64
	UserID         int64
	Language       string
	Code           string
	Input          sql.NullString
	ExpectedOutput sql.NullString
	Stdout         sql.NullString
	Stderr         sql.NullString
	ExitCode       sql.NullInt64
	WebhookUrl     sql.NullString
	CreatedAt      sql.NullTime
	UpdatedAt      sql.NullTime
}

type User struct {
	ID           int64
	Username     string
	PasswordHash string
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
}
